using System.Text;
using Microsoft.CodeAnalysis;

namespace Telepath.SourceGenerator;

internal static class ViewModelSourceRenderer
{
    public static string Render(
        INamedTypeSymbol viewModelType,
        IReadOnlyList<ViewModelGeneratedMember> members)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using global::R3;");
        source.AppendLine();

        if (!viewModelType.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ")
                .Append(viewModelType.ContainingNamespace.ToDisplayString())
                .AppendLine(";");
            source.AppendLine();
        }

        source.Append("partial class @")
            .Append(viewModelType.Name)
            .AppendLine();
        source.AppendLine("{");

        for (var index = 0; index < members.Count; index++)
        {
            if (index > 0)
            {
                source.AppendLine();
            }

            AppendMember(source, members[index]);
        }

        source.AppendLine("}");
        return source.ToString();
    }

    private static void AppendMember(StringBuilder source, ViewModelGeneratedMember member)
    {
        var backing = GeneratedMemberNames.BackingField(member.PropertyName);

        switch (member.Kind)
        {
            case ViewModelMemberKind.BindableField:
                source.Append("    private global::R3.BindableReactiveProperty<")
                    .Append(member.ValueTypeDisplay)
                    .Append(">? ")
                    .Append(backing)
                    .AppendLine(";");
                source.Append("    public global::R3.BindableReactiveProperty<")
                    .Append(member.ValueTypeDisplay)
                    .Append("> @")
                    .Append(member.PropertyName)
                    .AppendLine();
                source.Append("        => ")
                    .Append(backing)
                    .Append(" ??= Track(new global::R3.BindableReactiveProperty<")
                    .Append(member.ValueTypeDisplay)
                    .Append(">(@")
                    .Append(member.SourceMemberName)
                    .AppendLine("));");
                break;

            case ViewModelMemberKind.BindableMethod:
                source.Append("    private global::R3.BindableReactiveProperty<")
                    .Append(member.ValueTypeDisplay)
                    .Append(">? ")
                    .Append(backing)
                    .AppendLine(";");
                source.Append("    public global::R3.BindableReactiveProperty<")
                    .Append(member.ValueTypeDisplay)
                    .Append("> @")
                    .Append(member.PropertyName)
                    .AppendLine();
                source.Append("        => ")
                    .Append(backing)
                    .Append(" ??= Track(");
                AppendDerivedSource(source, member);
                source.Append(".ToBindableReactiveProperty(@")
                    .Append(member.SourceMemberName)
                    .Append('(');
                AppendFromValues(source, member);
                source.AppendLine(")));");
                break;

            case ViewModelMemberKind.Command:
                source.Append("    private global::R3.ReactiveCommand? ")
                    .Append(backing)
                    .AppendLine(";");
                source.Append("    public global::R3.ReactiveCommand @")
                    .Append(member.PropertyName)
                    .AppendLine();
                source.Append("        => ")
                    .Append(backing)
                    .Append(" ??= Track(");
                if (string.IsNullOrEmpty(member.CanExecute))
                {
                    source.Append("new global::R3.ReactiveCommand(_ => @")
                        .Append(member.SourceMemberName)
                        .AppendLine("()));");
                }
                else
                {
                    source.Append('@')
                        .Append(member.CanExecute);
                    if (member.CanExecuteIsMethod)
                    {
                        source.Append("()");
                    }

                    source.Append(".ToReactiveCommand(_ => @")
                        .Append(member.SourceMemberName)
                        .AppendLine("()));");
                }

                break;
        }
    }

    private static void AppendDerivedSource(StringBuilder source, ViewModelGeneratedMember member)
    {
        if (member.From.Length == 1)
        {
            source.Append('@')
                .Append(member.From[0])
                .Append(".Select(@")
                .Append(member.SourceMemberName)
                .Append(')');
            return;
        }

        source.Append("global::R3.Observable.CombineLatest(");
        for (var index = 0; index < member.From.Length; index++)
        {
            if (index > 0)
            {
                source.Append(", ");
            }

            source.Append('@').Append(member.From[index]);
        }

        source.Append(", @")
            .Append(member.SourceMemberName)
            .Append(')');
    }

    private static void AppendFromValues(StringBuilder source, ViewModelGeneratedMember member)
    {
        for (var index = 0; index < member.From.Length; index++)
        {
            if (index > 0)
            {
                source.Append(", ");
            }

            source.Append('@')
                .Append(member.From[index])
                .Append(".Value");
        }
    }
}
