using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Telepath.SourceGenerator;

internal static class ViewSourceRenderer
{
    public static string Render(
        INamedTypeSymbol viewType,
        string viewModelDisplay,
        bool hasOnReady,
        bool hasOnBind,
        IReadOnlyList<LinkToBinding> linkTos)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using Telepath.Godot;");
        source.AppendLine();

        if (!viewType.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ")
                .Append(viewType.ContainingNamespace.ToDisplayString())
                .AppendLine(";");
            source.AppendLine();
        }

        AppendContainingTypesStart(source, viewType.ContainingType);

        source.Append("partial class @")
            .Append(viewType.Name)
            .AppendLine();
        source.AppendLine("{");
        source.Append("    private global::Telepath.Godot.ViewLifecycle<")
            .Append(viewModelDisplay)
            .AppendLine(">? __telepathViewLifecycle;");
        source.AppendLine();
        source.Append("    private global::Telepath.Godot.ViewLifecycle<")
            .Append(viewModelDisplay)
            .AppendLine("> __TelepathViewLifecycle");
        source.AppendLine("        => __telepathViewLifecycle ??= new(");
        source.AppendLine("            this,");
        source.Append("            ")
            .Append(linkTos.Count > 0 ? "__TelepathOnReady" : hasOnReady ? "OnReady" : "static () => { }")
            .AppendLine(",");
        source.AppendLine("            CreateViewModel,");
        source.Append("            ")
            .Append(linkTos.Count > 0 ? "__TelepathOnBind" : "OnBind")
            .AppendLine(");");
        source.AppendLine();
        source.Append("    public ")
            .Append(viewModelDisplay)
            .AppendLine("? ViewModel");
        source.AppendLine("    {");
        source.AppendLine("        get => __TelepathViewLifecycle.ViewModel;");
        source.AppendLine("        set => __TelepathViewLifecycle.ViewModel = value;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public override partial void _Notification(int what)");
        source.AppendLine("    {");
        source.AppendLine("        base._Notification(what);");
        source.AppendLine("        __TelepathViewLifecycle.HandleNotification(what);");
        source.AppendLine("    }");

        if (linkTos.Count > 0)
        {
            source.AppendLine();
            AppendReady(source, linkTos, hasOnReady);
            source.AppendLine();
            AppendBind(source, viewModelDisplay, linkTos, hasOnBind);
        }

        source.AppendLine("}");

        AppendContainingTypesEnd(source, viewType.ContainingType);
        return source.ToString();
    }

    private static void AppendReady(
        StringBuilder source,
        IReadOnlyList<LinkToBinding> linkTos,
        bool hasOnReady)
    {
        source.AppendLine("    private void __TelepathOnReady()");
        source.AppendLine("    {");
        var resolvedMembers = new HashSet<string>(StringComparer.Ordinal);
        foreach (var linkTo in linkTos)
        {
            if (!resolvedMembers.Add(linkTo.TargetMemberName))
            {
                continue;
            }

            source.Append("        @")
                .Append(linkTo.TargetMemberName)
                .Append(" = GetNode<")
                .Append(linkTo.NodeTypeDisplay)
                .Append(">(")
                .Append(SymbolDisplay.FormatLiteral(linkTo.NodePath, quote: true))
                .AppendLine(");");
        }

        if (hasOnReady)
        {
            source.AppendLine("        OnReady();");
        }

        source.AppendLine("    }");
    }

    private static void AppendBind(
        StringBuilder source,
        string viewModelDisplay,
        IReadOnlyList<LinkToBinding> linkTos,
        bool hasOnBind)
    {
        source.Append("    private void __TelepathOnBind(")
            .Append(viewModelDisplay)
            .AppendLine(" vm, global::Telepath.Core.BindingSet bindings)");
        source.AppendLine("    {");
        foreach (var linkTo in linkTos)
        {
            source.Append("        bindings.")
                .Append(linkTo.BindMethodName)
                .Append("(vm.@")
                .Append(linkTo.ViewModelMember)
                .Append(", @")
                .Append(linkTo.TargetMemberName);
            if (linkTo.ParameterMemberName is not null)
            {
                source.Append(", () => @")
                    .Append(linkTo.ParameterMemberName)
                    .Append(linkTo.ParameterAccess);
            }

            if (linkTo.ConverterTypeDisplay is not null)
            {
                source.Append(", new ")
                    .Append(linkTo.ConverterTypeDisplay)
                    .Append("()");
            }

            source.AppendLine(");");
        }

        if (hasOnBind)
        {
            source.AppendLine("        OnBind(vm, bindings);");
        }

        source.AppendLine("    }");
    }

    private static void AppendContainingTypesStart(
        StringBuilder source,
        INamedTypeSymbol? containingType)
    {
        if (containingType is null)
        {
            return;
        }

        AppendContainingTypesStart(source, containingType.ContainingType);
        source.Append("partial ")
            .Append(containingType.TypeKind == TypeKind.Struct ? "struct @" : "class @")
            .Append(containingType.Name)
            .AppendLine();
        source.AppendLine("{");
    }

    private static void AppendContainingTypesEnd(
        StringBuilder source,
        INamedTypeSymbol? containingType)
    {
        while (containingType is not null)
        {
            source.AppendLine("}");
            containingType = containingType.ContainingType;
        }
    }
}