using System.Text;
using Microsoft.CodeAnalysis;

namespace Telepath.SourceGenerator;

internal static class ViewSourceRenderer
{
    public static string Render(
        INamedTypeSymbol viewType,
        string viewModelDisplay,
        bool hasOnReady)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");

        if (!viewType.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ")
                .Append(viewType.ContainingNamespace.ToDisplayString())
                .AppendLine(";");
            source.AppendLine();
        }

        AppendContainingTypesStart(source, viewType.ContainingType);

        source.Append("partial class @")
            .Append(viewType.Name)
            .AppendLine();
        source.AppendLine("{");
        source.Append("    private global::Telepath.Godot.ViewLifecycle<")
            .Append(viewModelDisplay)
            .AppendLine(">? __telepathViewLifecycle;");
        source.AppendLine();
        source.Append("    private global::Telepath.Godot.ViewLifecycle<")
            .Append(viewModelDisplay)
            .AppendLine("> __TelepathViewLifecycle");
        source.AppendLine("        => __telepathViewLifecycle ??= new(");
        source.AppendLine("            this,");
        source.Append("            ")
            .Append(hasOnReady ? "OnReady" : "static () => { }")
            .AppendLine(",");
        source.AppendLine("            CreateViewModel,");
        source.AppendLine("            OnBind);");
        source.AppendLine();
        source.Append("    public ")
            .Append(viewModelDisplay)
            .AppendLine("? ViewModel");
        source.AppendLine("    {");
        source.AppendLine("        get => __TelepathViewLifecycle.ViewModel;");
        source.AppendLine("        set => __TelepathViewLifecycle.ViewModel = value;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public override partial void _Notification(int what)");
        source.AppendLine("    {");
        source.AppendLine("        base._Notification(what);");
        source.AppendLine("        __TelepathViewLifecycle.HandleNotification(what);");
        source.AppendLine("    }");
        source.AppendLine("}");

        AppendContainingTypesEnd(source, viewType.ContainingType);
        return source.ToString();
    }

    private static void AppendContainingTypesStart(
        StringBuilder source,
        INamedTypeSymbol? containingType)
    {
        if (containingType is null)
        {
            return;
        }

        AppendContainingTypesStart(source, containingType.ContainingType);
        source.Append("partial ")
            .Append(containingType.TypeKind == TypeKind.Struct ? "struct @" : "class @")
            .Append(containingType.Name)
            .AppendLine();
        source.AppendLine("{");
    }

    private static void AppendContainingTypesEnd(
        StringBuilder source,
        INamedTypeSymbol? containingType)
    {
        while (containingType is not null)
        {
            source.AppendLine("}");
            containingType = containingType.ContainingType;
        }
    }
}
