using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Telepath.SourceGenerator;

internal static class ViewSourceRenderer
{
    public static string Render(
        INamedTypeSymbol viewType,
        string viewModelDisplay,
        bool hasOnReady,
        bool hasOnBind,
        IReadOnlyList<NodeInjection> injections,
        IReadOnlyList<ViewBinding> bindings)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using Telepath.Core;");
        source.AppendLine("using Telepath.Godot;");
        source.AppendLine();

        if (!viewType.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ")
                .Append(viewType.ContainingNamespace.ToDisplayString())
                .AppendLine(";");
            source.AppendLine();
        }

        AppendContainingTypesStart(source, viewType.ContainingType);

        var needsGeneratedReady = injections.Count > 0;
        var needsGeneratedBind = bindings.Count > 0;

        source.Append("partial class @")
            .Append(viewType.Name)
            .Append(" : global::Telepath.Godot.ITelepathView<")
            .Append(viewModelDisplay)
            .AppendLine(">");
        source.AppendLine("{");
        source.Append("    private global::Telepath.Godot.ViewLifecycle<")
            .Append(viewModelDisplay)
            .AppendLine(">? __telepathViewLifecycle;");
        source.AppendLine();
        source.Append("    private global::Telepath.Godot.ViewLifecycle<")
            .Append(viewModelDisplay)
            .AppendLine("> __TelepathViewLifecycle");
        source.AppendLine("        => __telepathViewLifecycle ??= new(");
        source.AppendLine("            this,");
        source.Append("            ")
            .Append(needsGeneratedReady ? "__TelepathOnReady" : hasOnReady ? "OnReady" : "static () => { }")
            .AppendLine(",");
        source.AppendLine("            CreateViewModel,");
        source.Append("            ")
            .Append(needsGeneratedBind ? "__TelepathOnBind" : "OnBind")
            .AppendLine(");");
        source.AppendLine();
        source.Append("    public ")
            .Append(viewModelDisplay)
            .AppendLine("? ViewModel");
        source.AppendLine("    {");
        source.AppendLine("        get => __TelepathViewLifecycle.ViewModel;");
        source.AppendLine("        set => __TelepathViewLifecycle.ViewModel = value;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public override partial void _Notification(int what)");
        source.AppendLine("    {");
        source.AppendLine("        base._Notification(what);");
        source.AppendLine("        __TelepathViewLifecycle.HandleNotification(what);");
        source.AppendLine("    }");

        if (needsGeneratedReady)
        {
            source.AppendLine();
            AppendReady(source, injections, hasOnReady);
        }

        if (needsGeneratedBind)
        {
            source.AppendLine();
            AppendBind(source, viewModelDisplay, bindings, hasOnBind);
        }

        source.AppendLine("}");

        AppendContainingTypesEnd(source, viewType.ContainingType);
        return source.ToString();
    }

    private static void AppendReady(
        StringBuilder source,
        IReadOnlyList<NodeInjection> injections,
        bool hasOnReady)
    {
        source.AppendLine("    private void __TelepathOnReady()");
        source.AppendLine("    {");
        foreach (var injection in injections)
        {
            source.Append("        @")
                .Append(injection.TargetMemberName)
                .Append(" = GetNode<")
                .Append(injection.NodeTypeDisplay)
                .Append(">(")
                .Append(SymbolDisplay.FormatLiteral(injection.NodePath, quote: true))
                .AppendLine(");");
        }

        if (hasOnReady)
        {
            source.AppendLine("        OnReady();");
        }

        source.AppendLine("    }");
    }

    private static void AppendBind(
        StringBuilder source,
        string viewModelDisplay,
        IReadOnlyList<ViewBinding> bindings,
        bool hasOnBind)
    {
        source.Append("    private void __TelepathOnBind(")
            .Append(viewModelDisplay)
            .AppendLine(" vm, global::Telepath.Core.BindingSet bindings)");
        source.AppendLine("    {");
        foreach (var binding in bindings)
        {
            if (binding.Kind == BindToKind.Command)
            {
                source.Append("        bindings.BindCommand(vm.@")
                    .Append(binding.ViewModelMember)
                    .Append(", @")
                    .Append(binding.TargetMemberName);
                if (binding.ParameterMemberName is not null)
                {
                    source.Append(", () => @")
                        .Append(binding.ParameterMemberName)
                        .Append(binding.ParameterAccess);
                }

                source.AppendLine(");");
                continue;
            }

            source.Append("        bindings.Bind(vm.@")
                .Append(binding.ViewModelMember)
                .Append(", @")
                .Append(binding.TargetMemberName)
                .Append(binding.TargetAccessor);
            if (binding.ConverterTypeDisplay is not null)
            {
                source.Append(", new ")
                    .Append(binding.ConverterTypeDisplay)
                    .Append("()");
            }
            else if (binding.ImplicitToString)
            {
                source.Append(", global::Telepath.Core.ToStringConverter.Convert");
            }

            source.AppendLine(");");
        }

        if (hasOnBind)
        {
            source.AppendLine("        OnBind(vm, bindings);");
        }

        source.AppendLine("    }");
    }

    private static void AppendContainingTypesStart(
        StringBuilder source,
        INamedTypeSymbol? containingType)
    {
        if (containingType is null)
        {
            return;
        }

        AppendContainingTypesStart(source, containingType.ContainingType);
        source.Append("partial ")
            .Append(containingType.TypeKind == TypeKind.Struct ? "struct @" : "class @")
            .Append(containingType.Name)
            .AppendLine();
        source.AppendLine("{");
    }

    private static void AppendContainingTypesEnd(
        StringBuilder source,
        INamedTypeSymbol? containingType)
    {
        while (containingType is not null)
        {
            source.AppendLine("}");
            containingType = containingType.ContainingType;
        }
    }
}
